# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldGame', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ninja',
        ),
    ]
